### PR TITLE
Add PiHole v6 driver

### PR DESCRIPTION
**Pull request by Bertware**
This PR adds an initial driver for PiHole v6:

- Adds support for PiHole v6 (currently in development, near release) which has a new API
- Adds several new capabilities including temperature, uptime and blocking status
- Adds action capabilities to restart dns, update gravity
- Adds trigger flow cards for a domain being queried (=blocked or allowed) or specifically blocked
- Adds trigger flow cards for a client sending a query (=blocked or allowed) or a query which is blocked
- Adds action flow cards to block or unblock a domain, to apply a block/allow to a pihole group
- Adds condition flow cards to check if a domain is blocked

flow cards
device

### CODE REVIEW

**Comment by Bertware** [comment]
Note: The new driver uses [typescript](https://apps.developer.homey.app/guides/tools/typescript#converting-an-existing-app-to-typescript). You must run `npm install` before trying to run the application. The original v5 driver is left untouched and still uses javascript.

**Comment by Bertware** [comment]
I discovered and added error handling for issues with DNS resolution. This may also be good to know for users of PiHole v5.x, as NodeJS cannot always resolve domains such as pihole.local, even when they are working in a webbrowser. In my case, they worked fine when running in Docker using `homey app run`,  but didn't work when running on Homey using `homey app install`.

The V6 driver shows a clear error when the domain name cannot be used, and suggest the user to configure the IP address instead. 
device unavailable error message on DNS resolution issues

**Comment by Bertware** [comment]
Added two more flow action cards to add/remove local DNS pointers, everything seems to be working fine now:
local dns action cards

**Comment by TroRon** [comment]
Hello Bertware

I've tidied up a bit and implemented your code as far as I could ....

However, I can't get the flow to fly, I've largely completed the overviews and translations.

If you still feel like it, you are welcome to participate further. Maybe I should also consider handing over the entire project to you?

Greetings

Ronny

**Pull request merged**
