### PR TITLE
Improved pairing flow, on/off button capability

### PR DESCRIPTION
**Pull request by Bertware**
Hi there!

This pull request improves the current pihole driver with two key features:
- An on/off button capability has been added. This capability was already present in the code, but not in the driver definition. I fixed an issue where the pihole state did not update afterwards, otherwise it works nicely
- The existing pairing flow was a bit unclear, and contained someones personal homey settings. Instead, I added auto-discovery (unfortunately by testing the entire subnet, as any sensible approach is impossible on Homey), which means most pihole-instances are picked up automatically. When trying to add these devices, the IP address and port number are already filled. When adding a device, the connection is tested, and different errors are shown if the ip. port, or api key are incorrect.

There are some other changes as well:
- I simplified some code in device.js for brevity and readability, one example being the registration of capability listeners. The behaviour is unchanged. For example, there is no need to keep track of multiple timeouts, and most methods can get their information directly from the parent (`this`), which allowed for cleaner, shorter code. This also fixes a bug, the interval was created 4 times (then cancelled 3 times) instead of creating it once. Some common code, such as getting the url including the port number, has been moved to a little method which makes it easier to keep track of which methods make api calls.
- I discovered there will be a v6 release of pihole in the near future with a different API. I therefore already adjusted the name for the current driver to include "v5.x" distinguishing it from the new driver in the future.

Known issues;
- Translations for the new error messages in the pairing process. An old, unused message was removed.

I tried to avoid reformatting the code so the diff would remain readable. Some lines did however contain trailing spaces which where automatically removed when I committed the file, which makes the diff for `device.js` seem larger than it is. 

Tested on a Homey 2023 pro.

### CODE REVIEW

**Comment by TroRon** [comment]
Hey

Thank you very much for your work.

I am a beginner myself and am glad to have your input, which I will gladly adopt.

Thank you very much :)

And if you see anything else, feel free.

Ronny

**Comment by Bertware** [comment]
Hi Ronny, thanks for the quick reply. Could you test with your existing setup to ensure existing flows did not break? There is no reason for them to do so, but since I only just started using the extension and added/removed my instance a lot during testing, I have nothing which could break either.

**Comment by TroRon** [comment]
In any case.

I'll check the whole thing briefly at my place this evening.

I can't get to it at the moment, my little daughter is demanding playtime ;)

I'll be in touch :)

**Comment by TroRon** [comment]
Looks good, my tests were also successful.

The flows are not interrupted :)

I've wanted to change the device detection for a long time, but didn't really know how. Now I have a great example :)

Many thanks for that.

I have switched the version as a test and now let it continue testing, if nothing more comes, it will go live :)

https://homey.app/en-us/app/ch.place4fun.pihole/PiHole-Control/test/

Translated with DeepL.com (free version)

**Pull request merged**
